In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
movies=pd.read_csv("tmdb_5000_movies.csv")
credits=pd.read_csv("tmdb_5000_credits.csv")

In [4]:
movies.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466

In [5]:
credits.head(2)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [6]:
movies=movies.merge(credits,on="title")

In [7]:
movies

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4804,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,9367,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,72766,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,231617,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,126186,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,25975,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [8]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [9]:
# genres
# id
# keywords
# title
# overview
# cast
# crew


movies=movies[['movie_id','title','keywords','genres','cast','crew','overview']]

movies.head()

In [10]:
movies.head(2)

,movie_id,title,keywords,genres,cast,crew,overview
0,19995,Avatar,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","Captain Barbossa, long believed to be dead, ha..."

In [11]:
#check missing data
movies.isnull().sum()

movie_id    0
title       0
keywords    0
genres      0
cast        0
crew        0
overview    3
dtype: int64

In [12]:
#removing missing value data
movies.dropna(inplace=True)

C:\Users\sharm\AppData\Local\Temp\ipykernel_16068\2848975366.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies.dropna(inplace=True)

In [13]:
movies.duplicated().sum()

0

In [14]:
#preprocessing the columns
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [15]:
#'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
#convert into ['Action','Adeventure','Fantasy','SciFi']

def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [16]:
import ast
#ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

In [17]:
movies['genres']=movies['genres'].apply(convert)

C:\Users\sharm\AppData\Local\Temp\ipykernel_16068\1567952790.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genres']=movies['genres'].apply(convert)

In [18]:
movies.head()

,movie_id,title,keywords,genres,cast,crew,overview
0,19995,Avatar,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[Action, Adventure, Fantasy, Science Fiction]","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[Adventure, Fantasy, Action]","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[Action, Adventure, Crime]","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[Action, Crime, Drama, Thriller]","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",Following the death of District Attorney Harve...
4,49529,John Carter,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[Action, Adventure, Science Fiction]","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","John Carter is a war-weary, former military ca..."

In [19]:
#here up we can see the genres column are preprocessed

In [20]:
#Now doing the same thing for keywords columns
movies['keywords']=movies['keywords'].apply(convert)

C:\Users\sharm\AppData\Local\Temp\ipykernel_16068\3243762908.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['keywords']=movies['keywords'].apply(convert)

In [21]:
movies.head()

,movie_id,title,keywords,genres,cast,crew,overview
0,19995,Avatar,"[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,"[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...","[Action, Crime, Drama, Thriller]","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",Following the death of District Attorney Harve...
4,49529,John Carter,"[based on novel, mars, medallion, space travel...","[Action, Adventure, Science Fiction]","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","John Carter is a war-weary, former military ca..."

In [22]:
#now here we taking the another column cast.Here we pickup only three imp cast 

def convert3(obj):
    L=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter!=3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [23]:
movies['cast']=movies['cast'].apply(convert3)

C:\Users\sharm\AppData\Local\Temp\ipykernel_16068\670030197.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['cast']=movies['cast'].apply(convert3)

In [24]:
movies.head()

,movie_id,title,keywords,genres,cast,crew,overview
0,19995,Avatar,"[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,"[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...","[Action, Crime, Drama, Thriller]","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",Following the death of District Attorney Harve...
4,49529,John Carter,"[based on novel, mars, medallion, space travel...","[Action, Adventure, Science Fiction]","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","John Carter is a war-weary, former military ca..."

In [25]:
##Now we are going for the crew column in which we take the job of director only

In [26]:
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append(i['name'])
            break;
    return L

In [27]:
movies['crew']=movies['crew'].apply(fetch_director)

C:\Users\sharm\AppData\Local\Temp\ipykernel_16068\766358383.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['crew']=movies['crew'].apply(fetch_director)

In [28]:
movies.head()

,movie_id,title,keywords,genres,cast,crew,overview
0,19995,Avatar,"[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,"[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...","[Action, Crime, Drama, Thriller]","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],Following the death of District Attorney Harve...
4,49529,John Carter,"[based on novel, mars, medallion, space travel...","[Action, Adventure, Science Fiction]","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],"John Carter is a war-weary, former military ca..."

In [29]:
# for overview
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [30]:
#since the overview are in string so we convert into list using lmbda function
movies['overview']=movies['overview'].apply(lambda x:x.split())

C:\Users\sharm\AppData\Local\Temp\ipykernel_16068\2964099475.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['overview']=movies['overview'].apply(lambda x:x.split())

In [31]:
movies.head()

,movie_id,title,keywords,genres,cast,crew,overview
0,19995,Avatar,"[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[ocean, drug abuse, exotic island, east india ...","[Adventure, Fantasy, Action]","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[spy, based on novel, secret agent, sequel, mi...","[Action, Adventure, Crime]","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[dc comics, crime fighter, terrorist, secret i...","[Action, Crime, Drama, Thriller]","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[based on novel, mars, medallion, space travel...","[Action, Adventure, Science Fiction]","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [32]:
#now se the overview convert into list

In [33]:
#now are going to remove spaces in words

movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])

0       [Action, Adventure, Fantasy, ScienceFiction]
1                       [Adventure, Fantasy, Action]
2                         [Action, Adventure, Crime]
3                   [Action, Crime, Drama, Thriller]
4                [Action, Adventure, ScienceFiction]
                            ...
4804                       [Action, Crime, Thriller]
4805                               [Comedy, Romance]
4806               [Comedy, Drama, Romance, TVMovie]
4807                                              []
4808                                   [Documentary]
Name: genres, Length: 4806, dtype: object

In [34]:
#now spaces are removed for eg: science fiction become sciencefiction

In [35]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

C:\Users\sharm\AppData\Local\Temp\ipykernel_16068\568931677.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
C:\Users\sharm\AppData\Local\Temp\ipykernel_16068\568931677.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
C:\Users\sharm\AppData\Local\Temp\ipykernel_16068\568931677.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
C:\Users\sharm\AppData\Local\Temp\ipykernel_16068\568931677.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [36]:
movies.head()

,movie_id,title,keywords,genres,cast,crew,overview
0,19995,Avatar,"[cultureclash, future, spacewar, spacecolony, ...","[Action, Adventure, Fantasy, ScienceFiction]","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[ocean, drugabuse, exoticisland, eastindiatrad...","[Adventure, Fantasy, Action]","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[spy, basedonnovel, secretagent, sequel, mi6, ...","[Action, Adventure, Crime]","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[dccomics, crimefighter, terrorist, secretiden...","[Action, Crime, Drama, Thriller]","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[basedonnovel, mars, medallion, spacetravel, p...","[Action, Adventure, ScienceFiction]","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [37]:
#Now we are going to create a column which name is tags in which we concate all four columns which we pre processed

In [38]:
movies['tags']=movies['genres']+movies['keywords']+movies['crew']

C:\Users\sharm\AppData\Local\Temp\ipykernel_16068\563297148.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags']=movies['genres']+movies['keywords']+movies['crew']

In [39]:
movies.head()

,movie_id,title,keywords,genres,cast,crew,overview,tags
0,19995,Avatar,"[cultureclash, future, spacewar, spacecolony, ...","[Action, Adventure, Fantasy, ScienceFiction]","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction, c..."
1,285,Pirates of the Caribbean: At World's End,"[ocean, drugabuse, exoticisland, eastindiatrad...","[Adventure, Fantasy, Action]","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action, ocean, drugabuse,..."
2,206647,Spectre,"[spy, basedonnovel, secretagent, sequel, mi6, ...","[Action, Adventure, Crime]","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime, spy, basedonnovel, ..."
3,49026,The Dark Knight Rises,"[dccomics, crimefighter, terrorist, secretiden...","[Action, Crime, Drama, Thriller]","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller, dccomics, cri..."
4,49529,John Carter,"[basedonnovel, mars, medallion, spacetravel, p...","[Action, Adventure, ScienceFiction]","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction, basedonnov..."

In [40]:
movies['tags'][0]

['Action',
 'Adventure',
 'Fantasy',
 'ScienceFiction',
 'cultureclash',
 'future',
 'spacewar',
 'spacecolony',
 'society',
 'spacetravel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alienplanet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'loveaffair',
 'antiwar',
 'powerrelations',
 'mindandsoul',
 '3d',
 'JamesCameron']

In [41]:
#creating new df for removing the uneccesay columns which is in tags
new_df=movies[['movie_id','title','overview','tags','cast','crew']]

In [42]:
new_df

,movie_id,title,overview,tags,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction, c...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action, ocean, drugabuse,...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime, spy, basedonnovel, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller, dccomics, cri...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction, basedonnov...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]
...,...,...,...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui...","[Action, Crime, Thriller, unitedstates–mexicob...","[CarlosGallardo, JaimedeHoyos, PeterMarquardt]",[RobertRodriguez]
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended...","[Comedy, Romance, EdwardBurns]","[EdwardBurns, KerryBishé, MarshaDietlein]",[EdwardBurns]
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,...","[Comedy, Drama, Romance, TVMovie, date, loveat...","[EricMabius, KristinBooth, CrystalLowe]",[ScottSmith]
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is...",[DanielHsia],"[DanielHenney, ElizaCoupe, BillPaxton]",[DanielHsia]
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi...","[Documentary, obsession, camcorder, crush, dre...","[DrewBarrymore, BrianHerzlinger, CoreyFeldman]",[BrianHerzlinger]

In [43]:
#now we are going to change words which is same but in verbs 2nd or 3r
%pip install nltk

Collecting nltk
  Using cached nltk-3.8.1-py3-none-any.whl (1.5 MB)
Collecting click (from nltk)
  Using cached click-8.1.7-py3-none-any.whl (97 kB)
Requirement already satisfied: joblib in c:\users\sharm\appdata\local\programs\python\python311\lib\site-packages (from nltk) (1.3.2)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2023.10.3-cp311-cp311-win_amd64.whl (269 kB)
                                              0.0/269.6 kB ? eta -:--:--
     ----                                  30.7/269.6 kB 660.6 kB/s eta 0:00:01
     --------                              61.4/269.6 kB 825.8 kB/s eta 0:00:01
     ---------------                      112.6/269.6 kB 819.2 kB/s eta 0:00:01
     -----------------------              174.1/269.6 kB 952.6 kB/s eta 0:00:01
     ------------------------------       225.3/269.6 kB 981.9 kB/s eta 0:00:01
     -------------------------------------- 269.6/269.6 kB 1.0 MB/s eta 0:00:00
Collecting tqdm (from nltk)
  Downloading tqdm-4.66.1-py3-none-any.whl (78 kB)
                                              0.0/78.3 kB ? eta -:--:--
     -------------------                    41.0/78.3 kB 960.0 kB/s eta 0:00:01
     ---------------------------------------- 78.3/78.3 kB 1.1 MB/s eta 0:00:00
Requirement already satisfied: colorama in c:\users\sharm\appdata\roaming\python\python311\site-packages (from click->nltk) (0.4.6)
Installing collected packages: tqdm, regex, click, nltk
Successfully installed click-8.1.7 nltk-3.8.1 regex-2023.10.3 tqdm-4.66.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [44]:
#now we convert the list into string 
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\sharm\AppData\Local\Temp\ipykernel_16068\1677686000.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [45]:
#import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [46]:
def stem(text):
    y=[]
    for i in text.split():
        ps.stem(i)
        y.append(ps.stem(i))
    return " ".join(y)

In [47]:
#here example of stem
['loved','lovoing','loves']
['love','love','love']

['love', 'love', 'love']

In [48]:
ps.stem('loving')

'love'

In [49]:
ps.stem('dancing')

'danc'

In [50]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\sharm\AppData\Local\Temp\ipykernel_16068\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [51]:
#now we convert the list into string 
#new_df['tags'].apply(lambda x:" ".join(x))

In [52]:
new_df['overview']=new_df['overview'].apply(lambda x:" ".join(x))

C:\Users\sharm\AppData\Local\Temp\ipykernel_16068\3998286566.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['overview']=new_df['overview'].apply(lambda x:" ".join(x))

In [53]:
#new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [54]:
new_df.head()

,movie_id,title,overview,tags,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",action adventur fantasi sciencefict culturecla...,"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",adventur fantasi action ocean drugabus exotici...,"[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,action adventur crime spi basedonnovel secreta...,"[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,action crime drama thriller dccomic crimefight...,"[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...",action adventur sciencefict basedonnovel mar m...,"[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [55]:
new_df['tags'][0]

'action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d jamescameron'

In [56]:
#convert into lower case
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\sharm\AppData\Local\Temp\ipykernel_16068\2115922633.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [57]:
new_df.head()

,movie_id,title,overview,tags,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",action adventur fantasi sciencefict culturecla...,"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",adventur fantasi action ocean drugabus exotici...,"[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,action adventur crime spi basedonnovel secreta...,"[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,action crime drama thriller dccomic crimefight...,"[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...",action adventur sciencefict basedonnovel mar m...,"[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [58]:
#vectorization=converting text into vectors.
#methods :Bag of Words

from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=500,stop_words='english')

In [59]:
cv.fit_transform(new_df['tags']).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [60]:
cv.fit_transform(new_df['tags']).toarray().shape

(4806, 500)

In [61]:
#this is the vectors
vectors=cv.fit_transform(new_df['tags']).toarray()

In [62]:
vectors[5]

array([0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [63]:
cv.get_feature_names()

AttributeError: 'CountVectorizer' object has no attribute 'get_feature_names'

In [ ]:
#these words occur most frequently

In [ ]:
#distance of individual movie to ither movie
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
similarity=cosine_similarity(vectors)

In [ ]:
list(enumerate(similarity[4]))

[(0, 0.5262348115842176),
 (1, 0.17541160386140586),
 (2, 0.33541019662496846),
 (3, 0.0912870929175277),
 (4, 1.0),
 (5, 0.19069251784911848),
 (6, 0.0912870929175277),
 (7, 0.4),
 (8, 0.12909944487358058),
 (9, 0.21081851067789195),
 (10, 0.30000000000000004),
 (11, 0.23904572186687872),
 (12, 0.2),
 (13, 0.31622776601683794),
 (14, 0.30000000000000004),
 (15, 0.25819888974716115),
 (16, 0.30000000000000004),
 (17, 0.31622776601683794),
 (18, 0.4242640687119285),
 (19, 0.23904572186687872),
 (20, 0.22360679774997896),
 (21, 0.3651483716701108),
 (22, 0.15811388300841897),
 (23, 0.11952286093343936),
 (24, 0.22360679774997896),
 (25, 0.11180339887498948),
 (26, 0.3651483716701108),
 (27, 0.3585685828003181),
 (28, 0.4767312946227962),
 (29, 0.22360679774997896),
 (30, 0.19069251784911848),
 (31, 0.4216370213557839),
 (32, 0.3),
 (33, 0.33541019662496846),
 (34, 0.0),
 (35, 0.33541019662496846),
 (36, 0.4472135954999579),
 (37, 0.25819888974716115),
 (38, 0.22360679774997896),
 (39, 0.31622776601683794),
 (40, 0.09534625892455924),
 (41, 0.5),
 (42, 0.1),
 (43, 0.19069251784911848),
 (44, 0.1414213562373095),
 (45, 0.22360679774997896),
 (46, 0.30000000000000004),
 (47, 0.5),
 (48, 0.1825741858350554),
 (49, 0.25819888974716115),
 (50, 0.282842712474619),
 (51, 0.4472135954999579),
 (52, 0.3585685828003181),
 (53, 0.25819888974716115),
 (54, 0.12909944487358058),
 (55, 0.2860387767736777),
 (56, 0.4242640687119285),
 (57, 0.0),
 (58, 0.15811388300841897),
 (59, 0.4743416490252569),
 (60, 0.11952286093343936),
 (61, 0.47809144373375745),
 (62, 0.31622776601683794),
 (63, 0.2),
 (64, 0.10540925533894598),
 (65, 0.08770580193070293),
 (66, 0.11180339887498948),
 (67, 0.3872983346207417),
 (68, 0.3585685828003181),
 (69, 0.2),
 (70, 0.3872983346207417),
 (71, 0.3651483716701108),
 (72, 0.31622776601683794),
 (73, 0.0),
 (74, 0.3585685828003181),
 (75, 0.282842712474619),
 (76, 0.2631174057921088),
 (77, 0.08770580193070293),
 (78, 0.19069251784911848),
 (79, 0.33541019662496846),
 (80, 0.10540925533894598),
 (81, 0.33541019662496846),
 (82, 0.2860387767736777),
 (83, 0.4743416490252569),
 (84, 0.33541019662496846),
 (85, 0.38138503569823695),
 (86, 0.25819888974716115),
 (87, 0.23904572186687872),
 (88, 0.2738612787525831),
 (89, 0.11952286093343936),
 (90, 0.12909944487358058),
 (91, 0.4743416490252569),
 (92, 0.0912870929175277),
 (93, 0.23904572186687872),
 (94, 0.3651483716701108),
 (95, 0.2176428750330035),
 (96, 0.30000000000000004),
 (97, 0.3872983346207417),
 (98, 0.31622776601683794),
 (99, 0.1),
 (100, 0.0),
 (101, 0.31622776601683794),
 (102, 0.5163977794943223),
 (103, 0.17541160386140586),
 (104, 0.2860387767736777),
 (105, 0.282842712474619),
 (106, 0.07254762501100116),
 (107, 0.22360679774997896),
 (108, 0.3651483716701108),
 (109, 0.23904572186687872),
 (110, 0.0),
 (111, 0.4),
 (112, 0.21081851067789195),
 (113, 0.10540925533894598),
 (114, 0.11180339887498948),
 (115, 0.0912870929175277),
 (116, 0.21081851067789195),
 (117, 0.2),
 (118, 0.0),
 (119, 0.07254762501100116),
 (120, 0.0),
 (121, 0.25819888974716115),
 (122, 0.27386127875258315),
 (123, 0.22360679774997902),
 (124, 0.2449489742783178),
 (125, 0.23008949665421113),
 (126, 0.31622776601683794),
 (127, 0.2631174057921088),
 (128, 0.11952286093343936),
 (129, 0.31622776601683794),
 (130, 0.11180339887498948),
 (131, 0.25819888974716115),
 (132, 0.4472135954999579),
 (133, 0.0),
 (134, 0.21081851067789195),
 (135, 0.0),
 (136, 0.10540925533894598),
 (137, 0.0),
 (138, 0.21081851067789195),
 (139, 0.149071198499986),
 (140, 0.1414213562373095),
 (141, 0.22360679774997896),
 (142, 0.11952286093343936),
 (143, 0.12909944487358058),
 (144, 0.07669649888473705),
 (145, 0.1414213562373095),
 (146, 0.1825741858350554),
 (147, 0.31622776601683794),
 (148, 0.1414213562373095),
 (149, 0.2449489742783178),
 (150, 0.4216370213557839),
 (151, 0.33541019662496846),
 (152, 0.19069251784911848),
 (153, 0.22360679774997896),
 (154, 0.0),
 (155, 0.1825741858350554),
 (156, 0.1825741858350554),
 (157, 0.38729833462074176),
 (158, 0.4242640687119285),
 (159, 0.12909944487358058),
 (160, 0.2631174057921088),
 (161, 0.0),
 (162, 0.1825741858350554),
 (163, 0.2),
 (164, 0.282842712474619),
 (165, 0.149071198499986),
 (166, 0.27386127875258315),
 (167, 0.282842712474619),
 (168, 0.4),
 (169, 0.3651483716701108),
 (170, 0.282842712474619),
 (171, 0.31622776601683794),
 (172, 0.10540925533894598),
 (173, 0.12909944487358058),
 (174, 0.30000000000000004),
 (175, 0.21081851067789195),
 (176, 0.1533929977694741),
 (177, 0.0),
 (178, 0.11952286093343936),
 (179, 0.282842712474619),
 (180, 0.149071198499986),
 (181, 0.10540925533894598),
 (182, 0.4216370213557839),
 (183, 0.29019050004400465),
 (184, 0.2),
 (185, 0.21081851067789195),
 (186, 0.1825741858350554),
 (187, 0.33541019662496846),
 (188, 0.0816496580927726),
 (189, 0.31622776601683794),
 (190, 0.31622776601683794),
 (191, 0.10540925533894598),
 (192, 0.0),
 (193, 0.4743416490252569),
 (194, 0.0),
 (195, 0.1414213562373095),
 (196, 0.1632993161855452),
 (197, 0.11180339887498948),
 (198, 0.11180339887498948),
 (199, 0.2),
 (200, 0.1825741858350554),
 (201, 0.11952286093343936),
 (202, 0.12909944487358058),
 (203, 0.33541019662496846),
 (204, 0.08451542547285167),
 (205, 0.31622776601683794),
 (206, 0.4743416490252569),
 (207, 0.3585685828003181),
 (208, 0.25819888974716115),
 (209, 0.1825741858350554),
 (210, 0.11952286093343936),
 (211, 0.0),
 (212, 0.31622776601683794),
 (213, 0.15811388300841897),
 (214, 0.0),
 (215, 0.149071198499986),
 (216, 0.25819888974716115),
 (217, 0.12909944487358058),
 (218, 0.1414213562373095),
 (219, 0.25819888974716115),
 (220, 0.33541019662496846),
 (221, 0.11180339887498948),
 (222, 0.282842712474619),
 (223, 0.31622776601683794),
 (224, 0.23904572186687872),
 (225, 0.21081851067789195),
 (226, 0.0),
 (227, 0.10540925533894598),
 (228, 0.3585685828003181),
 (229, 0.3872983346207417),
 (230, 0.33541019662496846),
 (231, 0.0),
 (232, 0.30000000000000004),
 (233, 0.4242640687119285),
 (234, 0.08770580193070293),
 (235, 0.10540925533894598),
 (236, 0.11952286093343936),
 (237, 0.25819888974716115),
 (238, 0.3508232077228117),
 (239, 0.1414213562373095),
 (240, 0.2),
 (241, 0.23904572186687872),
 (242, 0.3585685828003181),
 (243, 0.23904572186687872),
 (244, 0.282842712474619),
 (245, 0.22360679774997896),
 (246, 0.0912870929175277),
 (247, 0.0),
 (248, 0.08770580193070293),
 (249, 0.4472135954999579),
 (250, 0.0),
 (251, 0.282842712474619),
 (252, 0.08451542547285167),
 (253, 0.31622776601683794),
 (254, 0.08770580193070293),
 (255, 0.0),
 (256, 0.3585685828003181),
 (257, 0.23904572186687872),
 (258, 0.0),
 (259, 0.31622776601683794),
 (260, 0.5),
 (261, 0.074535599249993),
 (262, 0.35856858280031806),
 (263, 0.23904572186687872),
 (264, 0.0),
 (265, 0.0),
 (266, 0.33806170189140666),
 (267, 0.25819888974716115),
 (268, 0.11180339887498948),
 (269, 0.19069251784911848),
 (270, 0.27386127875258315),
 (271, 0.3508232077228117),
 (272, 0.0),
 (273, 0.07905694150420949),
 (274, 0.23904572186687872),
 (275, 0.1825741858350554),
 (276, 0.12909944487358058),
 (277, 0.21081851067789195),
 (278, 0.4216370213557839),
 (279, 0.23904572186687872),
 (280, 0.0),
 (281, 0.0),
 (282, 0.11180339887498948),
 (283, 0.0),
 (284, 0.0),
 (285, 0.1414213562373095),
 (286, 0.07669649888473705),
 (287, 0.08451542547285167),
 (288, 0.1),
 (289, 0.11952286093343936),
 (290, 0.282842712474619),
 (291, 0.25819888974716115),
 (292, 0.35856858280031806),
 (293, 0.0),
 (294, 0.11952286093343936),
 (295, 0.11180339887498948),
 (296, 0.06900655593423542),
 (297, 0.11952286093343936),
 (298, 0.0),
 (299, 0.1),
 (300, 0.2631174057921088),
 (301, 0.11952286093343936),
 (302, 0.15811388300841897),
 (303, 0.12909944487358058),
 (304, 0.31622776601683794),
 (305, 0.3265986323710904),
 (306, 0.282842712474619),
 (307, 0.23904572186687872),
 (308, 0.25819888974716115),
 (309, 0.12909944487358058),
 (310, 0.253546276418555),
 (311, 0.22360679774997896),
 (312, 0.282842712474619),
 (313, 0.1825741858350554),
 (314, 0.0),
 (315, 0.3651483716701108),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.282842712474619),
 (320, 0.15811388300841897),
 (321, 0.0),
 (322, 0.3627381250550058),
 (323, 0.0),
 (324, 0.12909944487358058),
 (325, 0.15811388300841897),
 (326, 0.0),
 (327, 0.0),
 (328, 0.0),
 (329, 0.33541019662496846),
 (330, 0.33541019662496846),
 (331, 0.1414213562373095),
 (332, 0.23904572186687872),
 (333, 0.11180339887498948),
 (334, 0.31622776601683794),
 (335, 0.25819888974716115),
 (336, 0.12909944487358058),
 (337, 0.282842712474619),
 (338, 0.0),
 (339, 0.19069251784911848),
 (340, 0.23904572186687872),
 (341, 0.1414213562373095),
 (342, 0.4472135954999579),
 (343, 0.0),
 (344, 0.22360679774997896),
 (345, 0.1414213562373095),
 (346, 0.0),
 (347, 0.0),
 (348, 0.2),
 (349, 0.10540925533894598),
 (350, 0.21081851067789195),
 (351, 0.0),
 (352, 0.22360679774997896),
 (353, 0.12909944487358058),
 (354, 0.08770580193070293),
 (355, 0.06900655593423542),
 (356, 0.23904572186687872),
 (357, 0.0),
 (358, 0.23904572186687872),
 (359, 0.11952286093343936),
 (360, 0.0),
 (361, 0.1825741858350554),
 (362, 0.4743416490252569),
 (363, 0.27386127875258315),
 (364, 0.0),
 (365, 0.23904572186687872),
 (366, 0.31622776601683794),
 (367, 0.0),
 (368, 0.282842712474619),
 (369, 0.23904572186687872),
 (370, 0.17541160386140586),
 (371, 0.4242640687119285),
 (372, 0.12909944487358058),
 (373, 0.4743416490252569),
 (374, 0.10540925533894598),
 (375, 0.1414213562373095),
 (376, 0.25819888974716115),
 (377, 0.0),
 (378, 0.0),
 (379, 0.31622776601683794),
 (380, 0.0),
 (381, 0.1825741858350554),
 (382, 0.0),
 (383, 0.282842712474619),
 (384, 0.1414213562373095),
 (385, 0.0),
 (386, 0.1632993161855452),
 (387, 0.11180339887498948),
 (388, 0.0),
 (389, 0.4743416490252569),
 (390, 0.0),
 (391, 0.10540925533894598),
 (392, 0.15811388300841897),
 (393, 0.0),
 (394, 0.1825741858350554),
 (395, 0.0),
 (396, 0.07905694150420949),
 (397, 0.0),
 (398, 0.0),
 (399, 0.11952286093343936),
 (400, 0.47809144373375745),
 (401, 0.0),
 (402, 0.22360679774997896),
 (403, 0.21081851067789195),
 (404, 0.0),
 (405, 0.12909944487358058),
 (406, 0.0),
 (407, 0.0),
 (408, 0.11952286093343936),
 (409, 0.0),
 (410, 0.21081851067789195),
 (411, 0.31622776601683794),
 (412, 0.4743416490252569),
 (413, 0.12909944487358058),
 (414, 0.1825741858350554),
 (415, 0.149071198499986),
 (416, 0.0),
 (417, 0.0),
 (418, 0.12909944487358058),
 (419, 0.3585685828003181),
 (420, 0.282842712474619),
 (421, 0.0),
 (422, 0.11952286093343936),
 (423, 0.0),
 (424, 0.2631174057921088),
 (425, 0.1632993161855452),
 (426, 0.22360679774997896),
 (427, 0.0),
 (428, 0.0912870929175277),
 (429, 0.0),
 (430, 0.0),
 (431, 0.0),
 (432, 0.11952286093343936),
 (433, 0.11952286093343936),
 (434, 0.0),
 (435, 0.0),
 (436, 0.0),
 (437, 0.10540925533894598),
 (438, 0.0),
 (439, 0.11952286093343936),
 (440, 0.0),
 (441, 0.12909944487358058),
 (442, 0.1632993161855452),
 (443, 0.0),
 (444, 0.0),
 (445, 0.0),
 (446, 0.16903085094570333),
 (447, 0.10540925533894598),
 (448, 0.0),
 (449, 0.22360679774997896),
 (450, 0.1414213562373095),
 (451, 0.1),
 (452, 0.0),
 (453, 0.11180339887498948),
 (454, 0.25819888974716115),
 (455, 0.06900655593423542),
 (456, 0.11180339887498948),
 (457, 0.31622776601683794),
 (458, 0.25819888974716115),
 (459, 0.1),
 (460, 0.0),
 (461, 0.31622776601683794),
 (462, 0.0),
 (463, 0.0),
 (464, 0.0),
 (465, 0.0),
 (466, 0.4743416490252569),
 (467, 0.282842712474619),
 (468, 0.10540925533894598),
 (469, 0.21081851067789195),
 (470, 0.0),
 (471, 0.0),
 (472, 0.23904572186687872),
 (473, 0.12909944487358058),
 (474, 0.0),
 (475, 0.21081851067789195),
 (476, 0.282842712474619),
 (477, 0.0),
 (478, 0.16903085094570333),
 (479, 0.282842712474619),
 (480, 0.33541019662496846),
 (481, 0.0),
 (482, 0.0),
 (483, 0.3872983346207417),
 (484, 0.12909944487358058),
 (485, 0.11952286093343936),
 (486, 0.282842712474619),
 (487, 0.282842712474619),
 (488, 0.11180339887498948),
 (489, 0.0),
 (490, 0.33541019662496846),
 (491, 0.35856858280031806),
 (492, 0.1825741858350554),
 (493, 0.0),
 (494, 0.0),
 (495, 0.5163977794943223),
 (496, 0.0),
 (497, 0.0),
 (498, 0.1825741858350554),
 (499, 0.0),
 (500, 0.12909944487358058),
 (501, 0.2738612787525831),
 (502, 0.3872983346207417),
 (503, 0.2738612787525831),
 (504, 0.0),
 (505, 0.22360679774997896),
 (506, 0.11180339887498948),
 (507, 0.47809144373375745),
 (508, 0.3872983346207417),
 (509, 0.0),
 (510, 0.22360679774997896),
 (511, 0.3585685828003181),
 (512, 0.11952286093343936),
 (513, 0.25819888974716115),
 (514, 0.22360679774997896),
 (515, 0.0),
 (516, 0.0),
 (517, 0.0),
 (518, 0.31622776601683794),
 (519, 0.0816496580927726),
 (520, 0.0),
 (521, 0.0),
 (522, 0.0),
 (523, 0.31622776601683794),
 (524, 0.0),
 (525, 0.08770580193070293),
 (526, 0.0),
 (527, 0.0),
 (528, 0.08770580193070293),
 (529, 0.15811388300841897),
 (530, 0.1414213562373095),
 (531, 0.23904572186687872),
 (532, 0.0),
 (533, 0.0),
 (534, 0.1414213562373095),
 (535, 0.31622776601683794),
 (536, 0.0),
 (537, 0.15811388300841897),
 (538, 0.0),
 (539, 0.3508232077228117),
 (540, 0.282842712474619),
 (541, 0.282842712474619),
 (542, 0.23904572186687872),
 (543, 0.25819888974716115),
 (544, 0.25819888974716115),
 (545, 0.11180339887498948),
 (546, 0.23904572186687872),
 (547, 0.21081851067789195),
 (548, 0.0),
 (549, 0.282842712474619),
 (550, 0.12909944487358058),
 (551, 0.1),
 (552, 0.0),
 (553, 0.0816496580927726),
 (554, 0.0),
 (555, 0.0),
 (556, 0.1414213562373095),
 (557, 0.0),
 (558, 0.0),
 (559, 0.0),
 (560, 0.1825741858350554),
 (561, 0.11952286093343936),
 (562, 0.0),
 (563, 0.0),
 (564, 0.22360679774997896),
 (565, 0.1),
 (566, 0.0912870929175277),
 (567, 0.0),
 (568, 0.282842712474619),
 (569, 0.11180339887498948),
 (570, 0.11952286093343936),
 (571, 0.10540925533894598),
 (572, 0.09534625892455924),
 (573, 0.1533929977694741),
 (574, 0.1414213562373095),
 (575, 0.11180339887498948),
 (576, 0.0),
 (577, 0.5163977794943223),
 (578, 0.0),
 (579, 0.10540925533894598),
 (580, 0.22360679774997896),
 (581, 0.4242640687119285),
 (582, 0.30000000000000004),
 (583, 0.0816496580927726),
 (584, 0.0),
 (585, 0.0),
 (586, 0.12909944487358058),
 (587, 0.3872983346207417),
 (588, 0.0),
 (589, 0.10540925533894598),
 (590, 0.1414213562373095),
 (591, 0.19069251784911848),
 (592, 0.1),
 (593, 0.0),
 (594, 0.15811388300841897),
 (595, 0.31622776601683794),
 (596, 0.22360679774997896),
 (597, 0.11180339887498948),
 (598, 0.0),
 (599, 0.1),
 (600, 0.31622776601683794),
 (601, 0.282842712474619),
 (602, 0.282842712474619),
 (603, 0.0),
 (604, 0.282842712474619),
 (605, 0.0),
 (606, 0.0),
 (607, 0.33541019662496846),
 (608, 0.0),
 (609, 0.33541019662496846),
 (610, 0.3651483716701108),
 (611, 0.12909944487358058),
 (612, 0.10540925533894598),
 (613, 0.1825741858350554),
 (614, 0.10540925533894598),
 (615, 0.12909944487358058),
 (616, 0.0),
 (617, 0.09534625892455924),
 (618, 0.253546276418555),
 (619, 0.0),
 (620, 0.0),
 (621, 0.23904572186687872),
 (622, 0.23904572186687872),
 (623, 0.0),
 (624, 0.35856858280031806),
 (625, 0.0),
 (626, 0.1),
 (627, 0.31622776601683794),
 (628, 0.0),
 (629, 0.22360679774997896),
 (630, 0.0),
 (631, 0.12909944487358058),
 (632, 0.15811388300841897),
 (633, 0.0),
 (634, 0.22360679774997896),
 (635, 0.0),
 (636, 0.0),
 (637, 0.0),
 (638, 0.0),
 (639, 0.0),
 (640, 0.25819888974716115),
 (641, 0.0),
 (642, 0.0),
 (643, 0.3585685828003181),
 (644, 0.21081851067789195),
 (645, 0.16903085094570333),
 (646, 0.0),
 (647, 0.0),
 (648, 0.0),
 (649, 0.0),
 (650, 0.0),
 (651, 0.0),
 (652, 0.0),
 (653, 0.12909944487358058),
 (654, 0.2860387767736777),
 (655, 0.1825741858350554),
 (656, 0.0),
 (657, 0.21081851067789195),
 (658, 0.23904572186687872),
 (659, 0.17541160386140586),
 (660, 0.21081851067789195),
 (661, 0.4216370213557839),
 (662, 0.0),
 (663, 0.0),
 (664, 0.31622776601683794),
 (665, 0.23904572186687872),
 (666, 0.0912870929175277),
 (667, 0.0),
 (668, 0.15811388300841897),
 (669, 0.1),
 (670, 0.0),
 (671, 0.25819888974716115),
 (672, 0.0),
 (673, 0.08770580193070293),
 (674, 0.282842712474619),
 (675, 0.25819888974716115),
 (676, 0.12909944487358058),
 (677, 0.1348399724926484),
 (678, 0.3651483716701108),
 (679, 0.0),
 (680, 0.11952286093343936),
 (681, 0.0),
 (682, 0.0),
 (683, 0.23904572186687872),
 (684, 0.0),
 (685, 0.11952286093343936),
 (686, 0.0),
 (687, 0.31622776601683794),
 (688, 0.0),
 (689, 0.12909944487358058),
 (690, 0.12909944487358058),
 (691, 0.282842712474619),
 (692, 0.16903085094570333),
 (693, 0.1414213562373095),
 (694, 0.23008949665421113),
 (695, 0.31622776601683794),
 (696, 0.07669649888473705),
 (697, 0.0),
 (698, 0.10540925533894598),
 (699, 0.0),
 (700, 0.11952286093343936),
 (701, 0.1414213562373095),
 (702, 0.07669649888473705),
 (703, 0.0),
 (704, 0.19069251784911848),
 (705, 0.0),
 (706, 0.1825741858350554),
 (707, 0.0),
 (708, 0.3),
 (709, 0.0),
 (710, 0.0),
 (711, 0.2),
 (712, 0.0),
 (713, 0.0),
 (714, 0.0),
 (715, 0.31622776601683794),
 (716, 0.1825741858350554),
 (717, 0.11952286093343936),
 (718, 0.282842712474619),
 (719, 0.0),
 (720, 0.12909944487358058),
 (721, 0.1414213562373095),
 (722, 0.0),
 (723, 0.22360679774997896),
 (724, 0.10540925533894598),
 (725, 0.0),
 (726, 0.0),
 (727, 0.0),
 (728, 0.23904572186687872),
 (729, 0.0),
 (730, 0.11952286093343936),
 (731, 0.23904572186687872),
 (732, 0.3585685828003181),
 (733, 0.0),
 (734, 0.1825741858350554),
 (735, 0.23904572186687872),
 (736, 0.15811388300841897),
 (737, 0.08451542547285167),
 (738, 0.0),
 (739, 0.1414213562373095),
 (740, 0.27386127875258315),
 (741, 0.11180339887498948),
 (742, 0.11952286093343936),
 (743, 0.0),
 (744, 0.1),
 (745, 0.15811388300841897),
 (746, 0.31622776601683794),
 (747, 0.12909944487358058),
 (748, 0.1825741858350554),
 (749, 0.0),
 (750, 0.08770580193070293),
 (751, 0.0),
 (752, 0.25819888974716115),
 (753, 0.1414213562373095),
 (754, 0.33541019662496846),
 (755, 0.30000000000000004),
 (756, 0.0),
 (757, 0.0),
 (758, 0.0),
 (759, 0.12909944487358058),
 (760, 0.0),
 (761, 0.12909944487358058),
 (762, 0.10540925533894598),
 (763, 0.0),
 (764, 0.0),
 (765, 0.0),
 (766, 0.0),
 (767, 0.19069251784911848),
 (768, 0.21081851067789195),
 (769, 0.15811388300841897),
 (770, 0.16903085094570333),
 (771, 0.0),
 (772, 0.0),
 (773, 0.25819888974716115),
 (774, 0.1414213562373095),
 (775, 0.1414213562373095),
 (776, 0.1414213562373095),
 (777, 0.21081851067789195),
 (778, 0.27386127875258315),
 (779, 0.10540925533894598),
 (780, 0.0),
 (781, 0.21081851067789195),
 (782, 0.23904572186687872),
 (783, 0.31622776601683794),
 (784, 0.149071198499986),
 (785, 0.11180339887498948),
 (786, 0.3651483716701108),
 (787, 0.25819888974716115),
 (788, 0.2),
 (789, 0.0),
 (790, 0.1414213562373095),
 (791, 0.31622776601683794),
 (792, 0.12909944487358058),
 (793, 0.11180339887498948),
 (794, 0.25819888974716115),
 (795, 0.0),
 (796, 0.0),
 (797, 0.0),
 (798, 0.0),
 (799, 0.38138503569823695),
 (800, 0.25819888974716115),
 (801, 0.0),
 (802, 0.0),
 (803, 0.0),
 (804, 0.15811388300841897),
 (805, 0.12909944487358058),
 (806, 0.0),
 (807, 0.1),
 (808, 0.23904572186687872),
 (809, 0.09534625892455924),
 (810, 0.0),
 (811, 0.0),
 (812, 0.17541160386140586),
 (813, 0.2631174057921088),
 (814, 0.1414213562373095),
 (815, 0.0),
 (816, 0.11952286093343936),
 (817, 0.0),
 (818, 0.11952286093343936),
 (819, 0.0),
 (820, 0.0),
 (821, 0.07905694150420949),
 (822, 0.0),
 (823, 0.1414213562373095),
 (824, 0.0),
 (825, 0.0),
 (826, 0.0),
 (827, 0.0),
 (828, 0.11180339887498948),
 (829, 0.0),
 (830, 0.10540925533894598),
 (831, 0.282842712474619),
 (832, 0.0),
 (833, 0.4),
 (834, 0.1632993161855452),
 (835, 0.0),
 (836, 0.31622776601683794),
 (837, 0.11952286093343936),
 (838, 0.38138503569823695),
 (839, 0.0),
 (840, 0.23904572186687872),
 (841, 0.15811388300841897),
 (842, 0.12909944487358058),
 (843, 0.11952286093343936),
 (844, 0.1414213562373095),
 (845, 0.0),
 (846, 0.0),
 (847, 0.0),

In [ ]:
sorted(list(enumerate(similarity[0])), reverse=True,key=lambda x:x[1])[1:9]

[(61, 0.628970902033151),
 (1194, 0.5661385170722979),
 (2333, 0.5661385170722979),
 (17, 0.5547001962252291),
 (83, 0.5547001962252291),
 (206, 0.5547001962252291),
 (466, 0.5547001962252291),
 (2378, 0.5547001962252291)]

In [ ]:
#index fetching
#new_df[new_df['title']=='Batman Begins'].index[0]

In [ ]:
sorted([3,1,6,4,44,6,32],reverse=True)

[44, 32, 6, 6, 4, 3, 1]

In [ ]:
#now we are going to create function for recommend movie
def recommend(movie):
    movie_index=new_df[new_df['title']==movie].index[0]
    
    distances=similarity[movie_index]
    movies_list=sorted(list(enumerate(distances)), reverse=True,key=lambda x:x[1])[1:6]
     
    for i in movies_list:
        print(new_df.iloc[i[0]].title)
        print(" ")
        print(new_df.iloc[i[0]].overview)
    
    return

In [ ]:
recommend("Avengers: Age of Ultron")

Ant-Man

['Armed', 'with', 'the', 'astonishing', 'ability', 'to', 'shrink', 'in', 'scale', 'but', 'increase', 'in', 'strength,', 'master', 'thief', 'Scott', 'Lang', 'must', 'embrace', 'his', 'inner-hero', 'and', 'help', 'his', 'mentor,', 'Doctor', 'Hank', 'Pym,', 'protect', 'the', 'secret', 'behind', 'his', 'spectacular', 'Ant-Man', 'suit', 'from', 'a', 'new', 'generation', 'of', 'towering', 'threats.', 'Against', 'seemingly', 'insurmountable', 'obstacles,', 'Pym', 'and', 'Lang', 'must', 'plan', 'and', 'pull', 'off', 'a', 'heist', 'that', 'will', 'save', 'the', 'world.']
Captain America: Civil War

['Following', 'the', 'events', 'of', 'Age', 'of', 'Ultron,', 'the', 'collective', 'governments', 'of', 'the', 'world', 'pass', 'an', 'act', 'designed', 'to', 'regulate', 'all', 'superhuman', 'activity.', 'This', 'polarizes', 'opinion', 'amongst', 'the', 'Avengers,', 'causing', 'two', 'factions', 'to', 'side', 'with', 'Iron', 'Man', 'or', 'Captain', 'America,', 'which', 'causes', 'an', 'epic', 'battle', 'between', 'former', 'allies.']
Captain America: The Winter Soldier

['After', 'the', 'cataclysmic', 'events', 'in', 'New', 'York', 'with', 'The', 'Avengers,', 'Steve', 'Rogers,', 'aka', 'Captain', 'America', 'is', 'living', 'quietly', 'in', 'Washington,', 'D.C.', 'and', 'trying', 'to', 'adjust', 'to', 'the', 'modern', 'world.', 'But', 'when', 'a', 'S.H.I.E.L.D.', 'colleague', 'comes', 'under', 'attack,', 'Steve', 'becomes', 'embroiled', 'in', 'a', 'web', 'of', 'intrigue', 'that', 'threatens', 'to', 'put', 'the', 'world', 'at', 'risk.', 'Joining', 'forces', 'with', 'the', 'Black', 'Widow,', 'Captain', 'America', 'struggles', 'to', 'expose', 'the', 'ever-widening', 'conspiracy', 'while', 'fighting', 'off', 'professional', 'assassins', 'sent', 'to', 'silence', 'him', 'at', 'every', 'turn.', 'When', 'the', 'full', 'scope', 'of', 'the', 'villainous', 'plot', 'is', 'revealed,', 'Captain', 'America', 'and', 'the', 'Black', 'Widow', 'enlist', 'the', 'help', 'of', 'a', 'new', 'ally,', 'the', 'Falcon.', 'However,', 'they', 'soon', 'find', 'themselves', 'up', 'against', 'an', 'unexpected', 'and', 'formidable', 'enemy—the', 'Winter', 'Soldier.']
Iron Man 3

['When', 'Tony', "Stark's", 'world', 'is', 'torn', 'apart', 'by', 'a', 'formidable', 'terrorist', 'called', 'the', 'Mandarin,', 'he', 'starts', 'an', 'odyssey', 'of', 'rebuilding', 'and', 'retribution.']
Thor: The Dark World

['Thor', 'fights', 'to', 'restore', 'order', 'across', 'the', 'cosmos…', 'but', 'an', 'ancient', 'race', 'led', 'by', 'the', 'vengeful', 'Malekith', 'returns', 'to', 'plunge', 'the', 'universe', 'back', 'into', 'darkness.', 'Faced', 'with', 'an', 'enemy', 'that', 'even', 'Odin', 'and', 'Asgard', 'cannot', 'withstand,', 'Thor', 'must', 'embark', 'on', 'his', 'most', 'perilous', 'and', 'personal', 'journey', 'yet,', 'one', 'that', 'will', 'reunite', 'him', 'with', 'Jane', 'Foster', 'and', 'force', 'him', 'to', 'sacrifice', 'everything', 'to', 'save', 'us', 'all.']

In [ ]:
#here how moview recommend by index
##new_df.iloc[1216].title

In [ ]:
import pickle

In [ ]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

In [ ]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [ ]:
new_df['overview'][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.']

In [ ]:
#similarity
pickle.dump(similarity,open('similarity.pkl','wb'))

In [ ]:
new_df['crew']

0           [JamesCameron]
1          [GoreVerbinski]
2              [SamMendes]
3       [ChristopherNolan]
4          [AndrewStanton]
               ...
4804     [RobertRodriguez]
4805         [EdwardBurns]
4806          [ScottSmith]
4807          [DanielHsia]
4808     [BrianHerzlinger]
Name: crew, Length: 4806, dtype: object